-- ============================================================================
-- SCRIPT SQL PARA SUPABASE (SEM COMANDOS 'DROP')
-- 100% Seguro - Não dispara avisos de operações destrutivas no Supabase
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabela de Departamentos
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    max_concurrent_vacations INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Funcionários
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cpf TEXT NOT NULL UNIQUE,
    registration_number TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'FUNCIONARIO',
    department_id BIGINT NOT NULL REFERENCES public.departments(id) ON DELETE RESTRICT,
    manager_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    hire_date DATE NOT NULL,
    job_title TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_employees_department_id ON public.employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_manager_id ON public.employees(manager_id);

-- 3. Tabela de Períodos Aquisitivos e Concessivos (CLT)
CREATE TABLE IF NOT EXISTS public.accrual_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    period_number INT NOT NULL,
    acquisitive_start DATE NOT NULL,
    acquisitive_end DATE NOT NULL,
    concessive_start DATE NOT NULL,
    concessive_end DATE NOT NULL,
    total_days_entitled INT DEFAULT 30 NOT NULL,
    days_taken INT DEFAULT 0 NOT NULL,
    days_sold INT DEFAULT 0 NOT NULL,
    days_remaining INT DEFAULT 30 NOT NULL,
    status TEXT DEFAULT 'EM_ANDAMENTO' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_concessive_order CHECK (concessive_start > acquisitive_start)
);

CREATE INDEX IF NOT EXISTS idx_accrual_periods_employee_id ON public.accrual_periods(employee_id);
CREATE INDEX IF NOT EXISTS idx_accrual_periods_concessive_end ON public.accrual_periods(concessive_end);

-- 4. Tabela de Solicitações de Férias
CREATE TABLE IF NOT EXISTS public.vacation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    accrual_period_id BIGINT NOT NULL REFERENCES public.accrual_periods(id) ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days INT NOT NULL,
    installment_number INT DEFAULT 1 NOT NULL,
    sell_days INT DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'PENDENTE' NOT NULL,
    has_department_overlap BOOLEAN DEFAULT FALSE NOT NULL,
    overlap_days INT DEFAULT 0 NOT NULL,
    conflicting_employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    notes TEXT,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_dates_order CHECK (end_date >= start_date),
    CONSTRAINT chk_fraction_min CHECK (duration_days >= 5),
    CONSTRAINT chk_installment_limit CHECK (installment_number BETWEEN 1 AND 3),
    CONSTRAINT chk_abono_limit CHECK (sell_days BETWEEN 0 AND 10)
);

CREATE INDEX IF NOT EXISTS idx_vacation_requests_employee_id ON public.vacation_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON public.vacation_requests(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON public.vacation_requests(status);

-- 5. Habilitar Row Level Security (RLS)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accrual_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacation_requests ENABLE ROW LEVEL SECURITY;

-- 6. Criação de Políticas RLS sem usar 'DROP' (Tratamento silencioso de duplicatas)
DO $$ 
BEGIN
    BEGIN
        CREATE POLICY "departments_policy" ON public.departments 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "employees_policy" ON public.employees 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "accrual_periods_policy" ON public.accrual_periods 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;

    BEGIN
        CREATE POLICY "vacation_requests_policy" ON public.vacation_requests 
            FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END $$;

-- 7. Carga Inicial de Dados (com ON CONFLICT seguro)
INSERT INTO public.departments (id, name, code, description) VALUES
(1, 'Tecnologia da Informação', 'TI', 'Engenharia de Software e Infraestrutura'),
(2, 'Recursos Humanos', 'RH', 'Departamento Pessoal e Treinamento'),
(3, 'Financeiro e Controladoria', 'FIN', 'Contabilidade e Compliance'),
(4, 'Operações e Logística', 'OPS', 'Supply Chain e Armazenagem'),
(5, 'Comercial e Vendas', 'COM', 'Expansão de Negócios')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.employees (id, name, email, cpf, registration_number, role, department_id, manager_id, hire_date, job_title) VALUES
(1, 'Carlos Eduardo Silveira', 'carlos.silveira@empresa.com.br', '111.222.333-44', 'MAT-1001', 'ADMIN', 1, NULL, '2021-02-15', 'Diretor de TI'),
(2, 'Ana Paula Mendes', 'ana.mendes@empresa.com.br', '222.333.444-55', 'MAT-1002', 'RH', 2, 1, '2022-03-01', 'Coordenadora de RH'),
(3, 'Juliana Castro', 'juliana.castro@empresa.com.br', '333.444.555-66', 'MAT-1003', 'RH', 2, 2, '2023-05-10', 'Analista de DP'),
(4, 'Rodrigo Albuquerque', 'rodrigo.ti@empresa.com.br', '444.555.666-77', 'MAT-1004', 'GESTOR', 1, 1, '2021-06-01', 'Tech Lead TI'),
(5, 'Lucas Pereira Rocha', 'lucas.rocha@empresa.com.br', '555.666.777-88', 'MAT-1005', 'FUNCIONARIO', 1, 4, '2022-08-15', 'Desenvolvedor Frontend'),
(6, 'Mariana Vasconcelos', 'mariana.v@empresa.com.br', '666.777.888-99', 'MAT-1006', 'FUNCIONARIO', 1, 4, '2023-01-20', 'Desenvolvedora Backend'),
(7, 'Felipe Sampaio', 'felipe.sampaio@empresa.com.br', '777.888.999-00', 'MAT-1007', 'FUNCIONARIO', 1, 4, '2024-02-10', 'Engenheiro DevOps')
ON CONFLICT (id) DO NOTHING;

-- 8. Sincronizar contadores de sequência
SELECT setval('public.departments_id_seq', COALESCE((SELECT MAX(id) FROM public.departments), 1));
SELECT setval('public.employees_id_seq', COALESCE((SELECT MAX(id) FROM public.employees), 1));
SELECT setval('public.accrual_periods_id_seq', COALESCE((SELECT MAX(id) FROM public.accrual_periods), 1));
SELECT setval('public.vacation_requests_id_seq', COALESCE((SELECT MAX(id) FROM public.vacation_requests), 1));
